// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type URLRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLRequest) Reset()         { *m = URLRequest{} }
func (m *URLRequest) String() string { return proto.CompactTextString(m) }
func (*URLRequest) ProtoMessage()    {}
func (*URLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *URLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLRequest.Unmarshal(m, b)
}
func (m *URLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLRequest.Marshal(b, m, deterministic)
}
func (m *URLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLRequest.Merge(m, src)
}
func (m *URLRequest) XXX_Size() int {
	return xxx_messageInfo_URLRequest.Size(m)
}
func (m *URLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_URLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_URLRequest proto.InternalMessageInfo

func (m *URLRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type HashedURLReply struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashedURLReply) Reset()         { *m = HashedURLReply{} }
func (m *HashedURLReply) String() string { return proto.CompactTextString(m) }
func (*HashedURLReply) ProtoMessage()    {}
func (*HashedURLReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *HashedURLReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashedURLReply.Unmarshal(m, b)
}
func (m *HashedURLReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashedURLReply.Marshal(b, m, deterministic)
}
func (m *HashedURLReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashedURLReply.Merge(m, src)
}
func (m *HashedURLReply) XXX_Size() int {
	return xxx_messageInfo_HashedURLReply.Size(m)
}
func (m *HashedURLReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HashedURLReply.DiscardUnknown(m)
}

var xxx_messageInfo_HashedURLReply proto.InternalMessageInfo

func (m *HashedURLReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type HashedUrlRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashedUrlRequest) Reset()         { *m = HashedUrlRequest{} }
func (m *HashedUrlRequest) String() string { return proto.CompactTextString(m) }
func (*HashedUrlRequest) ProtoMessage()    {}
func (*HashedUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *HashedUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashedUrlRequest.Unmarshal(m, b)
}
func (m *HashedUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashedUrlRequest.Marshal(b, m, deterministic)
}
func (m *HashedUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashedUrlRequest.Merge(m, src)
}
func (m *HashedUrlRequest) XXX_Size() int {
	return xxx_messageInfo_HashedUrlRequest.Size(m)
}
func (m *HashedUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashedUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashedUrlRequest proto.InternalMessageInfo

func (m *HashedUrlRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type URLReply struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Visited              int32    `protobuf:"varint,2,opt,name=visited,proto3" json:"visited,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLReply) Reset()         { *m = URLReply{} }
func (m *URLReply) String() string { return proto.CompactTextString(m) }
func (*URLReply) ProtoMessage()    {}
func (*URLReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *URLReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLReply.Unmarshal(m, b)
}
func (m *URLReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLReply.Marshal(b, m, deterministic)
}
func (m *URLReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLReply.Merge(m, src)
}
func (m *URLReply) XXX_Size() int {
	return xxx_messageInfo_URLReply.Size(m)
}
func (m *URLReply) XXX_DiscardUnknown() {
	xxx_messageInfo_URLReply.DiscardUnknown(m)
}

var xxx_messageInfo_URLReply proto.InternalMessageInfo

func (m *URLReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *URLReply) GetVisited() int32 {
	if m != nil {
		return m.Visited
	}
	return 0
}

func init() {
	proto.RegisterType((*URLRequest)(nil), "URLRequest")
	proto.RegisterType((*HashedURLReply)(nil), "HashedURLReply")
	proto.RegisterType((*HashedUrlRequest)(nil), "HashedUrlRequest")
	proto.RegisterType((*URLReply)(nil), "URLReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe3, 0xe2, 0x0a, 0x0d, 0xf2,
	0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x94, 0xb8, 0xf8, 0x3c, 0x12, 0x8b, 0x33, 0x52,
	0x53, 0xc0, 0xaa, 0x0a, 0x72, 0x2a, 0xb1, 0xa8, 0x51, 0xe3, 0x12, 0x80, 0xaa, 0x29, 0xca, 0x81,
	0x99, 0x24, 0xc4, 0xc5, 0x92, 0x91, 0x58, 0x9c, 0x01, 0x55, 0x06, 0x66, 0x2b, 0x99, 0x71, 0x71,
	0xe0, 0x36, 0x45, 0x48, 0x82, 0x8b, 0xbd, 0x2c, 0xb3, 0x38, 0xb3, 0x24, 0x35, 0x45, 0x82, 0x49,
	0x81, 0x51, 0x83, 0x35, 0x08, 0xc6, 0x35, 0x4a, 0xe0, 0xe2, 0x0c, 0xce, 0xc8, 0x2f, 0x2a, 0x49,
	0xcd, 0x4b, 0x2d, 0x12, 0xd2, 0xe4, 0x62, 0x87, 0x72, 0x84, 0xb8, 0xf5, 0x10, 0x4e, 0x97, 0xe2,
	0xd7, 0x43, 0x75, 0xa7, 0x12, 0x83, 0x90, 0x06, 0x17, 0x9b, 0x7b, 0x6a, 0x49, 0x68, 0x51, 0x8e,
	0x90, 0xa0, 0x1e, 0xba, 0x03, 0xa5, 0x38, 0xf5, 0x10, 0x2a, 0x93, 0xd8, 0xc0, 0x81, 0x61, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x94, 0x60, 0xaf, 0x71, 0x1d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShortenerClient is the client API for Shortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenerClient interface {
	Shorten(ctx context.Context, in *URLRequest, opts ...grpc.CallOption) (*HashedURLReply, error)
	GetUrl(ctx context.Context, in *HashedUrlRequest, opts ...grpc.CallOption) (*URLReply, error)
}

type shortenerClient struct {
	cc *grpc.ClientConn
}

func NewShortenerClient(cc *grpc.ClientConn) ShortenerClient {
	return &shortenerClient{cc}
}

func (c *shortenerClient) Shorten(ctx context.Context, in *URLRequest, opts ...grpc.CallOption) (*HashedURLReply, error) {
	out := new(HashedURLReply)
	err := c.cc.Invoke(ctx, "/Shortener/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetUrl(ctx context.Context, in *HashedUrlRequest, opts ...grpc.CallOption) (*URLReply, error) {
	out := new(URLReply)
	err := c.cc.Invoke(ctx, "/Shortener/GetUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServer is the server API for Shortener service.
type ShortenerServer interface {
	Shorten(context.Context, *URLRequest) (*HashedURLReply, error)
	GetUrl(context.Context, *HashedUrlRequest) (*URLReply, error)
}

func RegisterShortenerServer(s *grpc.Server, srv ShortenerServer) {
	s.RegisterService(&_Shortener_serviceDesc, srv)
}

func _Shortener_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Shortener/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).Shorten(ctx, req.(*URLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Shortener/GetUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetUrl(ctx, req.(*HashedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shortener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Shortener",
	HandlerType: (*ShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _Shortener_Shorten_Handler,
		},
		{
			MethodName: "GetUrl",
			Handler:    _Shortener_GetUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
